export const settingsStyles = {
  card: {
    background: '#ffffff',
    borderRadius: '12px',
    boxShadow: '0 4px 16px rgba(0, 0, 0, 0.08)',
    padding: '28px',
    marginBottom: '28px',
    maxWidth: '100%',
    marginLeft: 'auto',
    marginRight: 'auto',
    '&[data-theme="dark"]': {
      background: '#1f2a44',
      boxShadow: '0 4px 16px rgba(0, 0, 0, 0.25)',
    },
  },
  sectionTitle: {
    fontSize: '20px',
    fontWeight: '600',
    color: '#1e293b',
    marginBottom: '20px',
    letterSpacing: '0.3px',
    fontFamily: '"Inter", -apple-system, BlinkMacSystemFont, sans-serif',
    '&[data-theme="dark"]': {
      color: '#f1f5f9',
    },
  },
  label: {
    fontSize: '15px',
    fontWeight: '500',
    color: '#1e293b',
    marginBottom: '8px',
    '&[data-theme="dark"]': {
      color: '#d1d5db',
    },
  },
  form: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '20px',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '8px',
  },
  input: {
    padding: '14px 16px',
    border: '1px solid #e2e8f0',
    borderRadius: '8px',
    fontSize: '15px',
    color: '#1e293b',
    backgroundColor: '#ffffff',
    fontFamily: '"Inter", -apple-system, BlinkMacSystemFont, sans-serif',
    transition: 'all 0.2s ease',
    '&:focus': {
      outline: 'none',
      borderColor: '#3b82f6',
      boxShadow: '0 0 0 3px rgba(59, 130, 246, 0.3)',
    },
    '&:disabled': {
      backgroundColor: '#f8fafc',
      color: '#94a3b8',
      cursor: 'not-allowed',
      borderColor: '#e2e8f0',
    },
    '&[data-theme="dark"]': {
      backgroundColor: '#374151',
      color: '#d1d5db',
      borderColor: '#4b5563',
      '&:focus': {
        borderColor: '#93c5fd',
        boxShadow: '0 0 0 3px rgba(147, 197, 253, 0.3)',
      },
      '&:disabled': {
        backgroundColor: '#1f2a44',
        color: '#6b7280',
        borderColor: '#4b5563',
      },
    },
  },
  readOnlyText: {
    padding: '14px 16px',
    border: '1px solid #e2e8f0',
    borderRadius: '8px',
    fontSize: '15px',
    color: '#1e293b',
    backgroundColor: '#f8fafc', // Slightly gray to indicate non-editable
    fontFamily: '"Inter", -apple-system, BlinkMacSystemFont, sans-serif',
    '&[data-theme="dark"]': {
      backgroundColor: '#374151',
      color: '#d1d5db',
      borderColor: '#4b5563',
    },
  },
  submitButton: {
    padding: '12px 28px',
    border: 'none',
    borderRadius: '8px',
    fontSize: '15px',
    fontWeight: '500',
    color: '#ffffff',
    cursor: 'pointer',
    background: 'linear-gradient(180deg, #3b82f6, #2563eb)',
    fontFamily: '"Inter", -apple-system, BlinkMacSystemFont, sans-serif',
    transition: 'all 0.2s ease',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.1)',
    '&:hover': {
      background: 'linear-gradient(180deg, #60a5fa, #3b82f6)',
      boxShadow: '0 3px 10px rgba(59, 130, 246, 0.3)',
      transform: 'translateY(-1px)',
    },
    '&:active': {
      transform: 'translateY(0)',
      boxShadow: '0 1px 4px rgba(0, 0, 0, 0.1)',
    },
    '&:focus': {
      outline: 'none',
      boxShadow: '0 0 0 3px rgba(59, 130, 246, 0.3)',
    },
    '&:disabled': {
      background: 'linear-gradient(180deg, #e2e8f0, #d1d5db)',
      cursor: 'not-allowed',
      boxShadow: 'none',
      transform: 'none',
    },
  },
  errorMessage: {
    fontSize: '14px',
    color: '#dc2626',
    padding: '10px 14px',
    backgroundColor: '#fef2f2',
    borderRadius: '6px',
    fontFamily: '"Inter", -apple-system, BlinkMacSystemFont, sans-serif',
    '&[data-theme="dark"]': {
      backgroundColor: '#450a0a',
      color: '#f87171',
    },
  },
  successMessage: {
    fontSize: '14px',
    color: '#15803d',
    padding: '10px 14px',
    backgroundColor: '#f0fdf4',
    borderRadius: '6px',
    fontFamily: '"Inter", -apple-system, BlinkMacSystemFont, sans-serif',
    '&[data-theme="dark"]': {
      backgroundColor: '#052e16',
      color: '#86efac',
    },
  },
};